# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Hawk and Heron
email: andreasandpiper@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Handmade apparel and accessories


urls:
    - text: Hats
      url: /hats/
    - text: Jewelry
      url: /jewelry/
    - text: Purses
      url: /purses/
    - text: About
      url: /about/

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thehawkandheron.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
